-- Common LaTeX math commands for auto-completion in Quarto $ / $$ blocks.
-- Each entry: { label, detail, insert }
return {
  -- Greek / symbols
  { label = "\\alpha",        detail = "Greek alpha",          insert = "\\alpha " },
  { label = "\\beta",         detail = "Greek beta",           insert = "\\beta " },
  { label = "\\gamma",        detail = "Greek gamma",          insert = "\\gamma " },
  { label = "\\delta",        detail = "Greek delta",          insert = "\\delta " },
  { label = "\\epsilon",      detail = "Greek epsilon",        insert = "\\epsilon " },
  { label = "\\varepsilon",   detail = "Greek varepsilon",     insert = "\\varepsilon " },
  { label = "\\zeta",         detail = "Greek zeta",           insert = "\\zeta " },
  { label = "\\eta",          detail = "Greek eta",            insert = "\\eta " },
  { label = "\\theta",        detail = "Greek theta",          insert = "\\theta " },
  { label = "\\Theta",        detail = "Greek capital Theta",  insert = "\\Theta " },
  { label = "\\iota",         detail = "Greek iota",           insert = "\\iota " },
  { label = "\\kappa",        detail = "Greek kappa",          insert = "\\kappa " },
  { label = "\\lambda",       detail = "Greek lambda",         insert = "\\lambda " },
  { label = "\\Lambda",       detail = "Greek capital Lambda", insert = "\\Lambda " },
  { label = "\\mu",           detail = "Greek mu",             insert = "\\mu " },
  { label = "\\nu",           detail = "Greek nu",             insert = "\\nu " },
  { label = "\\xi",           detail = "Greek xi",             insert = "\\xi " },
  { label = "\\Xi",           detail = "Greek capital Xi",     insert = "\\Xi " },
  { label = "\\pi",           detail = "Greek pi",             insert = "\\pi " },
  { label = "\\Pi",           detail = "Greek capital Pi",     insert = "\\Pi " },
  { label = "\\rho",          detail = "Greek rho",            insert = "\\rho " },
  { label = "\\sigma",        detail = "Greek sigma",          insert = "\\sigma " },
  { label = "\\Sigma",        detail = "Greek capital Sigma",  insert = "\\Sigma " },
  { label = "\\tau",          detail = "Greek tau",            insert = "\\tau " },
  { label = "\\phi",          detail = "Greek phi",            insert = "\\phi " },
  { label = "\\varphi",       detail = "Greek varphi",         insert = "\\varphi " },
  { label = "\\Phi",          detail = "Greek capital Phi",    insert = "\\Phi " },
  { label = "\\chi",          detail = "Greek chi",            insert = "\\chi " },
  { label = "\\psi",          detail = "Greek psi",            insert = "\\psi " },
  { label = "\\Psi",          detail = "Greek capital Psi",    insert = "\\Psi " },
  { label = "\\omega",        detail = "Greek omega",          insert = "\\omega " },
  { label = "\\Omega",        detail = "Greek capital Omega",  insert = "\\Omega " },

  -- Operators
  { label = "\\sum",          detail = "Summation",            insert = "\\sum_{}^{}" },
  { label = "\\prod",         detail = "Product",              insert = "\\prod_{}^{}" },
  { label = "\\int",          detail = "Integral",             insert = "\\int_{}^{}" },
  { label = "\\iint",         detail = "Double integral",      insert = "\\iint_{}^{}" },
  { label = "\\iiint",        detail = "Triple integral",      insert = "\\iiint_{}^{}" },
  { label = "\\oint",         detail = "Contour integral",     insert = "\\oint_{}^{}" },
  { label = "\\lim",          detail = "Limit",                insert = "\\lim_{} " },
  { label = "\\infty",        detail = "Infinity",             insert = "\\infty " },
  { label = "\\partial",      detail = "Partial derivative",   insert = "\\partial " },
  { label = "\\nabla",        detail = "Gradient / del",       insert = "\\nabla " },

  -- Relations
  { label = "\\leq",          detail = "Less than or equal",   insert = "\\leq " },
  { label = "\\geq",          detail = "Greater than or equal",insert = "\\geq " },
  { label = "\\ll",           detail = "Much less than",       insert = "\\ll " },
  { label = "\\gg",           detail = "Much greater than",    insert = "\\gg " },
  { label = "\\approx",       detail = "Approximately",        insert = "\\approx " },
  { label = "\\sim",          detail = "Similar to",           insert = "\\sim " },
  { label = "\\simeq",        detail = "Similar / equal",      insert = "\\simeq " },
  { label = "\\equiv",        detail = "Equivalent",           insert = "\\equiv " },
  { label = "\\propto",       detail = "Proportional to",      insert = "\\propto " },
  { label = "\\perp",         detail = "Perpendicular",        insert = "\\perp " },
  { label = "\\models",       detail = "Models",               insert = "\\models " },
  { label = "\\mid",          detail = "Given / conditional",  insert = "\\mid " },

  -- Set theory
  { label = "\\subset",      detail = "Subset",               insert = "\\subset " },
  { label = "\\supset",      detail = "Superset",             insert = "\\supset " },
  { label = "\\subseteq",    detail = "Subset or equal",      insert = "\\subseteq " },
  { label = "\\supseteq",    detail = "Superset or equal",    insert = "\\supseteq " },
  { label = "\\cup",         detail = "Union",                insert = "\\cup " },
  { label = "\\cap",         detail = "Intersection",         insert = "\\cap " },
  { label = "\\emptyset",    detail = "Empty set",            insert = "\\emptyset " },
  { label = "\\varnothing",  detail = "Empty set (variant)",  insert = "\\varnothing " },
  { label = "\\in",          detail = "Element of",           insert = "\\in " },
  { label = "\\notin",       detail = "Not element of",       insert = "\\notin " },
  { label = "\\ni",          detail = "Contains as member",   insert = "\\ni " },

  -- Arrows
  { label = "\\to",          detail = "Right arrow",          insert = "\\to " },
  { label = "\\rightarrow",  detail = "Right arrow",          insert = "\\rightarrow " },
  { label = "\\Rightarrow",  detail = "Implies",              insert = "\\Rightarrow " },
  { label = "\\leftarrow",   detail = "Left arrow",           insert = "\\leftarrow " },
  { label = "\\Leftarrow",   detail = "Implied by",           insert = "\\Leftarrow " },
  { label = "\\mapsto",      detail = "Maps to",              insert = "\\mapsto " },
  { label = "\\implies",     detail = "Implies (long)",       insert = "\\implies " },
  { label = "\\iff",         detail = "If and only if",       insert = "\\iff " },

  -- Accents / hats
  { label = "\\hat",         detail = "Hat accent",           insert = "\\hat{}" },
  { label = "\\widehat",     detail = "Wide hat",             insert = "\\widehat{}" },
  { label = "\\tilde",       detail = "Tilde accent",         insert = "\\tilde{}" },
  { label = "\\widetilde",   detail = "Wide tilde",           insert = "\\widetilde{}" },
  { label = "\\bar",         detail = "Bar accent",           insert = "\\bar{}" },
  { label = "\\vec",         detail = "Vector accent",        insert = "\\vec{}" },
  { label = "\\dot",         detail = "Dot accent",           insert = "\\dot{}" },
  { label = "\\ddot",        detail = "Double dot accent",    insert = "\\ddot{}" },

  -- Functions
  { label = "\\sin",         detail = "Sine",                 insert = "\\sin " },
  { label = "\\cos",         detail = "Cosine",               insert = "\\cos " },
  { label = "\\tan",         detail = "Tangent",              insert = "\\tan " },
  { label = "\\log",         detail = "Logarithm",            insert = "\\log " },
  { label = "\\ln",          detail = "Natural log",          insert = "\\ln " },
  { label = "\\exp",         detail = "Exponential",          insert = "\\exp " },
  { label = "\\max",         detail = "Maximum",              insert = "\\max " },
  { label = "\\min",         detail = "Minimum",              insert = "\\min " },
  { label = "\\sup",         detail = "Supremum",             insert = "\\sup " },
  { label = "\\inf",         detail = "Infimum",              insert = "\\inf " },
  { label = "\\det",         detail = "Determinant",          insert = "\\det " },
  { label = "\\Pr",          detail = "Probability",          insert = "\\Pr " },
  { label = "\\arg",         detail = "Argument",             insert = "\\arg " },
  { label = "\\dim",         detail = "Dimension",            insert = "\\dim " },

  -- Probability / statistics
  { label = "\\mathbb{E}",   detail = "Expected value",       insert = "\\mathbb{E}" },
  { label = "\\mathbb{V}",   detail = "Variance",             insert = "\\mathbb{V}" },
  { label = "\\operatorname{Var}", detail = "Variance",       insert = "\\operatorname{Var}" },
  { label = "\\operatorname{Cov}", detail = "Covariance",     insert = "\\operatorname{Cov}" },
  { label = "\\operatorname{Corr}", detail = "Correlation",   insert = "\\operatorname{Corr}" },
  { label = "\\mathcal{N}",  detail = "Normal distribution",  insert = "\\mathcal{N}" },
  { label = "\\mathcal{U}",  detail = "Uniform distribution",insert = "\\mathcal{U}" },
  { label = "\\mathcal{B}",  detail = "Beta / Binomial",      insert = "\\mathcal{B}" },
  { label = "\\mathcal{G}",  detail = "Gamma",                insert = "\\mathcal{G}" },
  { label = "\\sim",         detail = "Distributed as",       insert = "\\sim " },

  -- Brackets / delimiters
  { label = "\\{",           detail = "Curly brace",          insert = "\\{ }" },
  { label = "\\}",           detail = "Closing brace",        insert = "\\}" },
  { label = "\\langle",      detail = "Left angle bracket",   insert = "\\langle " },
  { label = "\\rangle",      detail = "Right angle bracket",  insert = "\\rangle " },
  { label = "\\lfloor",      detail = "Left floor",           insert = "\\lfloor " },
  { label = "\\rfloor",      detail = "Right floor",          insert = "\\rfloor " },
  { label = "\\lceil",       detail = "Left ceiling",         insert = "\\lceil " },
  { label = "\\rceil",       detail = "Right ceiling",        insert = "\\rceil " },

  -- Spacing
  { label = "\\;",           detail = "Thick space",          insert = "\\; " },
  { label = "\\:",           detail = "Medium space",         insert = "\\: " },
  { label = "\\,",           detail = "Thin space",           insert = "\\, " },
  { label = "\\!",           detail = "Negative thin space",  insert = "\\! " },
  { label = "\\quad",        detail = "Quad space",           insert = "\\quad " },
  { label = "\\qquad",       detail = "Double quad space",    insert = "\\qquad " },
}
